# Generated by Django 3.0.6 on 2020-06-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
