# Generated by Django 3.0.6 on 2020-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0005_auto_20200629_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(choices=[('FET', 'Faculty of Engineering and Technology'), ('Agriculture Faculty', 'Faculty of Agriculture'), ('Science Faculty', 'Faculty of Science and Environment'), ('Arts Facults', 'Faculty of Arts'), ('Management Faculty', 'Faculty of Rural Development and Business Management')], default='FET', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_history',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
